// Auto-generated by `nubase pull` — do not edit manually.

import type { Ticket, TicketInsert, TicketUpdate } from "./ticket.js";

export interface NubaseEntities {
  ticket: {
    row: Ticket;
    insert: TicketInsert;
    update: TicketUpdate;
  };
}
