// Auto-generated by `nubase pull` — do not edit manually.

export interface Ticket {
  id: number;
  workspace_id: number;
  title: string;
  description: string | null;
  assignee_email: string | null;
}

export interface TicketInsert {
  workspace_id: number;
  title: string;
  description?: string | null;
  assignee_email?: string | null;
}

export interface TicketUpdate {
  workspace_id?: number;
  title?: string;
  description?: string | null;
  assignee_email?: string | null;
}
