// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: deleteTicket.sql
// Hash:   sha256:2256365eb6ba1f70
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type DeleteTicketParams = {
  id: number;
  workspace_id: number;
};

export type DeleteTicketRow = {
  id: number;
};

const SQL = `DELETE FROM tickets
WHERE id = $1 AND workspace_id = $2
RETURNING id
`;

export async function deleteTicket(
  db: Client | Pool | PoolClient,
  params: DeleteTicketParams,
): Promise<DeleteTicketRow[]> {
  const result = await db.query<DeleteTicketRow>(SQL, [
    params.id,
    params.workspace_id,
  ]);
  return result.rows;
}
