// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: getTicket.sql
// Hash:   sha256:e316d256c7e8b57b
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type GetTicketParams = {
  id: number;
  workspace_id: number;
};

export type GetTicketRow = {
  id: number;
  title: string;
  description: string | null;
  assignee_id: number | null;
};

const SQL = `SELECT id, title, description, assignee_id
FROM tickets
WHERE id = $1 AND workspace_id = $2
`;

export async function getTicket(
  db: Client | Pool | PoolClient,
  params: GetTicketParams,
): Promise<GetTicketRow[]> {
  const result = await db.query<GetTicketRow>(SQL, [
    params.id,
    params.workspace_id,
  ]);
  return result.rows;
}
