// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: getTicketById.sql
// Hash:   sha256:8eb8783120167a31
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type GetTicketByIdParams = {
  id: number;
};

export type GetTicketByIdRow = {
  id: number;
  workspace_id: number;
  title: string;
  description: string | null;
  assignee_id: number | null;
};

const SQL = `SELECT id, workspace_id, title, description, assignee_id
FROM tickets
WHERE id = $1
`;

export async function getTicketById(
  db: Client | Pool | PoolClient,
  params: GetTicketByIdParams,
): Promise<GetTicketByIdRow[]> {
  const result = await db.query<GetTicketByIdRow>(SQL, [params.id]);
  return result.rows;
}
