// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: insertTicket.sql
// Hash:   sha256:a5f2bf54232f7c9f
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type InsertTicketParams = {
  workspace_id: number;
  title: string;
  description: string;
  assignee_id: number;
};

export type InsertTicketRow = {
  id: number;
  title: string;
  description: string | null;
  assignee_id: number | null;
};

const SQL = `INSERT INTO tickets (workspace_id, title, description, assignee_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, assignee_id
`;

export async function insertTicket(
  db: Client | Pool | PoolClient,
  params: InsertTicketParams,
): Promise<InsertTicketRow[]> {
  const result = await db.query<InsertTicketRow>(SQL, [
    params.workspace_id,
    params.title,
    params.description,
    params.assignee_id,
  ]);
  return result.rows;
}
