// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: listTickets.sql
// Hash:   sha256:b2a33025c04056c2
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type ListTicketsParams = {
  workspace_id: number;
  q: string;
  title: string;
  description: string;
  assignee_ids: number[];
};

export type ListTicketsRow = {
  id: number;
  title: string;
  description: string | null;
  assignee_id: number | null;
  assignee_name: string;
  assignee_email: string;
};

const SQL = `SELECT
  t.id,
  t.title,
  t.description,
  t.assignee_id,
  u.display_name AS assignee_name,
  u.email AS assignee_email
FROM tickets t
LEFT JOIN users u ON u.id = t.assignee_id
WHERE t.workspace_id = $1
  AND ($2::text IS NULL OR t.title ILIKE $2 OR t.description ILIKE $2)
  AND ($3::text IS NULL OR t.title ILIKE $3)
  AND ($4::text IS NULL OR t.description ILIKE $4)
  AND ($5::int[] IS NULL OR t.assignee_id = ANY($5))
`;

export async function listTickets(
  db: Client | Pool | PoolClient,
  params: ListTicketsParams,
): Promise<ListTicketsRow[]> {
  const result = await db.query<ListTicketsRow>(SQL, [
    params.workspace_id,
    params.q,
    params.title,
    params.description,
    params.assignee_ids,
  ]);
  return result.rows;
}
