// ───────────────────────────────────────────────────────────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: updateTicket.sql
// Hash:   sha256:2b3a10de84d89475
// ───────────────────────────────────────────────────────────────────────────

import type { Client, Pool, PoolClient } from "pg";

export type UpdateTicketParams = {
  update_title: boolean;
  title: string;
  update_description: boolean;
  description: string;
  update_assignee_id: boolean;
  assignee_id: number;
  id: number;
  workspace_id: number;
};

export type UpdateTicketRow = {
  id: number;
  title: string;
  description: string | null;
  assignee_id: number | null;
};

const SQL = `UPDATE tickets
SET
  title = CASE WHEN $1 THEN $2 ELSE title END,
  description = CASE WHEN $3 THEN $4 ELSE description END,
  assignee_id = CASE WHEN $5 THEN $6 ELSE assignee_id END
WHERE id = $7 AND workspace_id = $8
RETURNING id, title, description, assignee_id
`;

export async function updateTicket(
  db: Client | Pool | PoolClient,
  params: UpdateTicketParams,
): Promise<UpdateTicketRow[]> {
  const result = await db.query<UpdateTicketRow>(SQL, [
    params.update_title,
    params.title,
    params.update_description,
    params.description,
    params.update_assignee_id,
    params.assignee_id,
    params.id,
    params.workspace_id,
  ]);
  return result.rows;
}
