/**
 * This file was generated by kysely-codegen.
 * Regenerate with: npx nubase db codegen
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Tickets {
  assigneeId: number | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  workspaceId: number;
}

export interface Users {
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  passwordHash: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserWorkspaces {
  createdAt: Generated<Timestamp | null>;
  userId: number;
  workspaceId: number;
}

export interface Workspaces {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  tickets: Tickets;
  users: Users;
  userWorkspaces: UserWorkspaces;
  workspaces: Workspaces;
}
