import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "intro",
        "getting-started",
        "create-nubase-app",
        "development-environment",
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "schema",
        "resources",
        "searching",
        "frontend",
        "authentication",
        "dashboards",
      ],
    },
    {
      type: "category",
      label: "Layouts",
      items: ["layouts", "form-layouts", "table-layouts"],
    },
    {
      type: "category",
      label: "Advanced",
      items: ["computed-metadata", "e2e-testing"],
    },
    {
      type: "category",
      label: "Database",
      items: ["configuration", "cli"],
    },
    {
      type: "category",
      label: "Typed SQL",
      items: [
        "typed-sql/overview",
        "typed-sql/writing-queries",
        "typed-sql/generated-code",
        "typed-sql/cli-usage",
        "typed-sql/caveats",
      ],
    },
    {
      type: "category",
      label: "Internals",
      items: [
        { type: "autogenerated", dirName: "internals" },
      ],
    },
    {
      type: "category",
      label: "Development Findings",
      items: [
        { type: "autogenerated", dirName: "development-findings" },
      ],
    },
    {
      type: "category",
      label: "Technical Decisions",
      items: [
        { type: "autogenerated", dirName: "technical-decisions" },
      ],
    },
  ],
};

export default sidebars;
