/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _NubaseMigrations {
  appliedAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface PgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jitDeformCount: Int8 | null;
  jitDeformTime: number | null;
  jitEmissionCount: Int8 | null;
  jitEmissionTime: number | null;
  jitFunctions: Int8 | null;
  jitGenerationTime: number | null;
  jitInliningCount: Int8 | null;
  jitInliningTime: number | null;
  jitOptimizationCount: Int8 | null;
  jitOptimizationTime: number | null;
  localBlkReadTime: number | null;
  localBlksDirtied: Int8 | null;
  localBlksHit: Int8 | null;
  localBlksRead: Int8 | null;
  localBlksWritten: Int8 | null;
  localBlkWriteTime: number | null;
  maxExecTime: number | null;
  maxPlanTime: number | null;
  meanExecTime: number | null;
  meanPlanTime: number | null;
  minExecTime: number | null;
  minmaxStatsSince: Timestamp | null;
  minPlanTime: number | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  sharedBlkReadTime: number | null;
  sharedBlksDirtied: Int8 | null;
  sharedBlksHit: Int8 | null;
  sharedBlksRead: Int8 | null;
  sharedBlksWritten: Int8 | null;
  sharedBlkWriteTime: number | null;
  statsSince: Timestamp | null;
  stddevExecTime: number | null;
  stddevPlanTime: number | null;
  tempBlkReadTime: number | null;
  tempBlksRead: Int8 | null;
  tempBlksWritten: Int8 | null;
  tempBlkWriteTime: number | null;
  toplevel: boolean | null;
  totalExecTime: number | null;
  totalPlanTime: number | null;
  userid: number | null;
  walBytes: Numeric | null;
  walFpi: Int8 | null;
  walRecords: Int8 | null;
}

export interface PgStatStatementsInfo {
  dealloc: Int8 | null;
  statsReset: Timestamp | null;
}

export interface Teams {
  description: string | null;
  id: Generated<number>;
  name: string;
  workspaceId: number;
}

export interface Tickets {
  assigneeId: number | null;
  description: string | null;
  id: Generated<number>;
  teamId: number | null;
  title: string;
  workspaceId: number;
}

export interface Users {
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  passwordHash: string;
  teamId: number | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserWorkspaces {
  createdAt: Generated<Timestamp | null>;
  userId: number;
  workspaceId: number;
}

export interface Workspaces {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  _NubaseMigrations: _NubaseMigrations;
  pgStatStatements: PgStatStatements;
  pgStatStatementsInfo: PgStatStatementsInfo;
  teams: Teams;
  tickets: Tickets;
  users: Users;
  userWorkspaces: UserWorkspaces;
  workspaces: Workspaces;
}
