services:
  postgresql:
    container_name: nubase-db-dev
    image: "postgres:17.5"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
      - ./postgresql-init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=questlog
      - POSTGRES_USER=questlog
      - POSTGRES_PASSWORD=questlog
