import type { PgColumn, PgEnum, PgTable } from "@nubase/pg";
import { pgTypeToTs, singularize, toPascalCase } from "./pg-to-ts.js";

// ---------------------------------------------------------------------------
// Schema metadata input (what the server sends back from GET /api/nubase/schema)
// ---------------------------------------------------------------------------

export interface SchemaMetadata {
  schemaVersion: string;
  tables: Record<string, TableMetadata>;
  enums: Record<string, EnumMetadata>;
}

export interface TableMetadata {
  name: string;
  columns: Record<string, ColumnMetadata>;
}

export interface ColumnMetadata {
  name: string;
  dataType: string;
  udtName: string;
  isNullable: boolean;
  defaultValue: string | null;
  isIdentity: boolean;
}

export interface EnumMetadata {
  name: string;
  values: string[];
}

// ---------------------------------------------------------------------------
// Convert PgSchema tables/enums → SchemaMetadata
// ---------------------------------------------------------------------------

export function pgTableToMetadata(table: PgTable): TableMetadata {
  const columns: Record<string, ColumnMetadata> = {};
  for (const [colName, col] of Object.entries(table.columns)) {
    columns[colName] = pgColumnToMetadata(col);
  }
  return { name: table.name, columns };
}

export function pgColumnToMetadata(col: PgColumn): ColumnMetadata {
  return {
    name: col.name,
    dataType: col.dataType,
    udtName: col.udtName,
    isNullable: col.isNullable,
    defaultValue: col.defaultValue,
    isIdentity: col.isIdentity,
  };
}

export function pgEnumToMetadata(pgEnum: PgEnum): EnumMetadata {
  return {
    name: pgEnum.name,
    values: pgEnum.values,
  };
}

// ---------------------------------------------------------------------------
// Generate TypeScript files from schema metadata
// ---------------------------------------------------------------------------

export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Generate all TypeScript type files from schema metadata.
 * Returns an array of { path, content } to be written to disk.
 */
export function generateTypes(schema: SchemaMetadata): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const entityNames: string[] = [];

  // Generate enum types
  const enumTypes = new Map<string, string>();
  for (const [, enumMeta] of Object.entries(schema.enums)) {
    enumTypes.set(enumMeta.name, toPascalCase(enumMeta.name));
  }

  // Generate per-entity files
  for (const [tableName, table] of Object.entries(schema.tables)) {
    const entityName = singularize(tableName);
    const pascalName = toPascalCase(entityName);
    entityNames.push(entityName);

    const content = generateEntityFile(
      pascalName,
      table,
      schema.enums,
      enumTypes,
    );
    files.push({ path: `${entityName}.ts`, content });
  }

  // Generate entity-map.ts
  files.push({
    path: "entity-map.ts",
    content: generateEntityMapFile(entityNames),
  });

  // Generate entities.ts (barrel for all entity types)
  files.push({
    path: "entities.ts",
    content: generateEntitiesBarrelFile(entityNames),
  });

  // Generate index.ts
  files.push({
    path: "index.ts",
    content: generateIndexFile(),
  });

  return files;
}

function generateEntityFile(
  pascalName: string,
  table: TableMetadata,
  enums: Record<string, EnumMetadata>,
  enumTypes: Map<string, string>,
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by `nubase pull` — do not edit manually.");
  lines.push("");

  // Collect any enum types used by this entity
  const usedEnums = new Set<string>();
  for (const col of Object.values(table.columns)) {
    if (col.dataType === "USER-DEFINED" && enums[col.udtName]) {
      usedEnums.add(col.udtName);
    }
  }

  // Emit enum type aliases
  for (const enumName of usedEnums) {
    const enumMeta = enums[enumName];
    if (enumMeta) {
      const typeName = enumTypes.get(enumName) ?? toPascalCase(enumName);
      const unionType = enumMeta.values.map((v) => `"${v}"`).join(" | ");
      lines.push(`export type ${typeName} = ${unionType};`);
      lines.push("");
    }
  }

  // Row interface (full row from DB)
  lines.push(`export interface ${pascalName} {`);
  for (const col of Object.values(table.columns)) {
    const tsType = resolveColumnType(col, enums, enumTypes);
    const nullable = col.isNullable ? " | null" : "";
    lines.push(`  ${col.name}: ${tsType}${nullable};`);
  }
  lines.push("}");
  lines.push("");

  // Insert interface (omit identity/auto-generated columns, make nullable/default optional)
  const insertFields: string[] = [];
  for (const col of Object.values(table.columns)) {
    if (col.isIdentity) continue; // Skip auto-generated ID
    const tsType = resolveColumnType(col, enums, enumTypes);
    const nullable = col.isNullable ? " | null" : "";
    const optional = col.isNullable || col.defaultValue !== null ? "?" : "";
    insertFields.push(`  ${col.name}${optional}: ${tsType}${nullable};`);
  }
  lines.push(`export interface ${pascalName}Insert {`);
  lines.push(...insertFields);
  lines.push("}");
  lines.push("");

  // Update interface (all fields optional, omit identity)
  const updateFields: string[] = [];
  for (const col of Object.values(table.columns)) {
    if (col.isIdentity) continue;
    const tsType = resolveColumnType(col, enums, enumTypes);
    const nullable = col.isNullable ? " | null" : "";
    updateFields.push(`  ${col.name}?: ${tsType}${nullable};`);
  }
  lines.push(`export interface ${pascalName}Update {`);
  lines.push(...updateFields);
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function resolveColumnType(
  col: ColumnMetadata,
  enums: Record<string, EnumMetadata>,
  enumTypes: Map<string, string>,
): string {
  if (col.dataType === "USER-DEFINED" && enums[col.udtName]) {
    return enumTypes.get(col.udtName) ?? toPascalCase(col.udtName);
  }
  const tsType = pgTypeToTs(col.udtName, col.dataType);
  if (tsType === "USER_DEFINED") {
    return "unknown";
  }
  return tsType;
}

function generateEntityMapFile(entityNames: string[]): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by `nubase pull` — do not edit manually.");
  lines.push("");

  // Import all entity types
  for (const entityName of entityNames) {
    const pascalName = toPascalCase(entityName);
    lines.push(
      `import type { ${pascalName}, ${pascalName}Insert, ${pascalName}Update } from "./${entityName}.js";`,
    );
  }
  lines.push("");

  // Generate the NubaseEntities type (must be `type`, not `interface`, to satisfy EntityMap index signature)
  lines.push("export type NubaseEntities = {");
  for (const entityName of entityNames) {
    const pascalName = toPascalCase(entityName);
    lines.push(`  ${entityName}: {`);
    lines.push(`    row: ${pascalName};`);
    lines.push(`    insert: ${pascalName}Insert;`);
    lines.push(`    update: ${pascalName}Update;`);
    lines.push("  };");
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateEntitiesBarrelFile(entityNames: string[]): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by `nubase pull` — do not edit manually.");
  lines.push("");
  for (const entityName of entityNames) {
    const pascalName = toPascalCase(entityName);
    lines.push(
      `export type { ${pascalName}, ${pascalName}Insert, ${pascalName}Update } from "./${entityName}.js";`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function generateIndexFile(): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by `nubase pull` — do not edit manually.");
  lines.push("");
  lines.push('export type { NubaseEntities } from "./entity-map.js";');
  lines.push('export * from "./entities.js";');
  lines.push("");
  return lines.join("\n");
}
