import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import {
  createTestContext,
  destroyTestContext,
  resetDatabase,
  SOURCE_URL,
  setupSchema,
  type TestContext,
} from "../../testing/test-helpers";
import { generateAll } from "./generate-all";

describe("generateAll - integration", () => {
  let ctx: TestContext;
  let tmp: string;

  beforeAll(async () => {
    ctx = await createTestContext();
  });

  afterAll(async () => {
    await destroyTestContext(ctx);
  });

  beforeEach(async () => {
    await resetDatabase(ctx.source);
    await setupSchema(
      ctx.source,
      `
      CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        display_name TEXT
      );
      CREATE TABLE tickets (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        status TEXT NOT NULL,
        author_id INTEGER NOT NULL REFERENCES users(id)
      );
      `,
    );
    tmp = await mkdtemp(path.join(os.tmpdir(), "nubase-generate-"));
  });

  async function write(relPath: string, content: string): Promise<void> {
    const abs = path.join(tmp, relPath);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, content, "utf8");
  }

  async function read(relPath: string): Promise<string> {
    return readFile(path.join(tmp, relPath), "utf8");
  }

  it("generates a .ts for a simple SELECT", async () => {
    await write(
      "tickets/getTicketById.sql",
      "SELECT id, title, status FROM tickets WHERE id = :id",
    );

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.errors).toEqual([]);
    expect(result.generated).toHaveLength(1);
    expect(result.deleted).toEqual([]);

    const content = await read("tickets/getTicketById.ts");
    expect(content).toContain("// Generated by @nubase/pg");
    expect(content).toContain("// Source: getTicketById.sql");
    expect(content).toContain(
      'import type { Client, Pool, PoolClient } from "pg";',
    );
    expect(content).toContain("export type GetTicketByIdParams = {");
    expect(content).toContain("  id: number;");
    expect(content).toContain("export type GetTicketByIdRow = {");
    expect(content).toContain("  id: number;");
    expect(content).toContain("  title: string;");
    expect(content).toContain("  status: string;");
    expect(content).toContain("export async function getTicketById(");
    expect(content).toContain("): Promise<GetTicketByIdRow[]> {");
  });

  it("generates a command function for a DELETE without RETURNING", async () => {
    await write(
      "tickets/deleteTicket.sql",
      "DELETE FROM tickets WHERE id = :id",
    );

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.errors).toEqual([]);
    const content = await read("tickets/deleteTicket.ts");
    expect(content).toContain("): Promise<{ rowCount: number }> {");
    expect(content).not.toContain("DeleteTicketRow");
  });

  it("collects errors for queries with undefined columns", async () => {
    await write("tickets/broken.sql", "SELECT titel FROM tickets");

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.errors).toHaveLength(1);
    expect(result.errors[0]?.code).toBe("PG_PARSE_ERROR");
    expect(result.errors[0]?.diagnostic).toContain("42703");
    expect(result.errors[0]?.diagnostic).toContain("titel");
  });

  it("processes multiple files and reports them all", async () => {
    await write(
      "tickets/getTicket.sql",
      "SELECT id FROM tickets WHERE id = :id",
    );
    await write(
      "users/getUser.sql",
      "SELECT id, email FROM users WHERE id = :id",
    );
    await write("users/broken.sql", "SELECT notacol FROM users");

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.generated).toHaveLength(2);
    expect(result.errors).toHaveLength(1);
  });

  it("applies @json overrides to row fields", async () => {
    // Add a metadata column for this test.
    await setupSchema(
      ctx.source,
      `ALTER TABLE tickets ADD COLUMN metadata jsonb`,
    );
    await write(
      "tickets/getTicketMeta.sql",
      `-- @json metadata: import("@/schemas").TicketMetadata
SELECT id, metadata FROM tickets WHERE id = :id`,
    );

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.errors).toEqual([]);
    const content = await read("tickets/getTicketMeta.ts");
    expect(content).toContain(
      'import type { TicketMetadata } from "@/schemas";',
    );
    expect(content).toContain("  metadata: TicketMetadata;");
    expect(content).not.toContain("metadata: unknown");
  });

  it("deletes orphaned .ts files on regeneration", async () => {
    await write(
      "tickets/stayQuery.sql",
      "SELECT id FROM tickets WHERE id = :id",
    );
    // Pre-existing orphaned generated file
    await write(
      "tickets/goneQuery.ts",
      `// Generated by @nubase/pg. DO NOT EDIT.
// Source: goneQuery.sql
// Hash:   sha256:0000000000000000
export const x = 1;
`,
    );

    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });

    expect(result.generated).toHaveLength(1);
    expect(result.deleted).toHaveLength(1);
    expect(result.deleted[0]).toContain("goneQuery.ts");
  });

  it("--check mode fails on stale files", async () => {
    await write(
      "tickets/getTicket.sql",
      "SELECT id FROM tickets WHERE id = :id",
    );
    // No generated .ts exists — check should report stale.
    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
      check: true,
    });
    expect(result.stale).toHaveLength(1);
    expect(result.generated).toEqual([]);
  });

  it("--check mode passes when files are up to date", async () => {
    await write(
      "tickets/getTicket.sql",
      "SELECT id FROM tickets WHERE id = :id",
    );
    // First, generate.
    await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });
    // Then check.
    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
      check: true,
    });
    expect(result.stale).toEqual([]);
    expect(result.unchanged).toHaveLength(1);
  });

  it("handles an empty data-layer directory", async () => {
    const result = await generateAll({
      databaseUrl: SOURCE_URL,
      dataLayerDir: tmp,
    });
    expect(result.generated).toEqual([]);
    expect(result.errors).toEqual([]);
  });
});
