/**
 * Render the final `.ts` file content for a generated query.
 *
 * Takes a fully resolved `QueryModel` (assembled by `generate-query.ts`
 * from the vendored `IQueryTypes` + the named-params preprocessor output +
 * the JSON annotations) and produces a plain string that can be written
 * to disk.
 *
 * Responsibilities:
 * - Capitalize the query function name to derive `ParamsType` / `RowType`.
 * - Emit the header comment with source filename + content hash.
 * - Emit hoisted top-level type imports (from `@json` overrides).
 * - Emit the `SQL` constant (the rewritten SQL with `$N` placeholders).
 * - Emit the function body — one of two shapes:
 *   - returns rows (RowDescription had fields): `Promise<Row[]>`
 *   - command (no RowDescription): `Promise<{ rowCount: number }>`
 */

import { hoistImports } from "./hoist-imports.js";

export interface QueryParamModel {
  name: string;
  tsType: string;
}

export interface QueryRowFieldModel {
  name: string;
  tsType: string;
  nullable: boolean;
}

export interface QueryModel {
  /** Function name — matches the .sql file basename. */
  name: string;
  /** Source `.sql` file basename (used in the header comment). */
  sourceBasename: string;
  /** Content hash of the source SQL (used by `--check` mode). */
  sourceHash: string;
  /** Rewritten SQL with `$1`, `$2`, ... placeholders, ready to send to `pg.query`. */
  sql: string;
  /** Named parameters in positional order. */
  params: QueryParamModel[];
  /**
   * Row fields returned by the query, in order.
   *
   * `null` means the query produces no rows (e.g. `DELETE` without
   * `RETURNING`) and the generated function returns `{ rowCount }`.
   */
  rowFields: QueryRowFieldModel[] | null;
}

export interface RenderOptions {
  /**
   * If true, indent the embedded `SQL` constant using a raw template literal
   * that preserves newlines. Otherwise collapse to a single line. Default true.
   */
  multilineSql?: boolean;
}

const HEADER_LINE =
  "// ───────────────────────────────────────────────────────────────────────────";

function capitalize(s: string): string {
  return s.length > 0 ? s[0]?.toUpperCase() + s.slice(1) : s;
}

function renderHeader(sourceBasename: string, sourceHash: string): string {
  return [
    HEADER_LINE,
    "// Generated by @nubase/pg. DO NOT EDIT.",
    `// Source: ${sourceBasename}`,
    `// Hash:   sha256:${sourceHash}`,
    HEADER_LINE,
  ].join("\n");
}

function renderSqlConst(sql: string, multiline: boolean): string {
  if (!multiline || !sql.includes("\n")) {
    // Single-line — use regular double-quoted string with \\n escapes.
    const escaped = sql.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `const SQL = "${escaped}";`;
  }
  // Multi-line — use a template literal. Escape any literal backticks in the SQL.
  const escaped = sql
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  return `const SQL = \`${escaped}\`;`;
}

function renderParamsType(
  name: string,
  params: QueryParamModel[],
): string | null {
  if (params.length === 0) return null;
  const lines = [`export type ${name}Params = {`];
  for (const p of params) {
    lines.push(`  ${p.name}: ${p.tsType};`);
  }
  lines.push("};");
  return lines.join("\n");
}

function renderRowType(name: string, rowFields: QueryRowFieldModel[]): string {
  const lines = [`export type ${name}Row = {`];
  for (const f of rowFields) {
    const t =
      f.nullable && !/\|\s*null\b/.test(f.tsType)
        ? `${f.tsType} | null`
        : f.tsType;
    lines.push(`  ${f.name}: ${t};`);
  }
  lines.push("};");
  return lines.join("\n");
}

function renderSignatureLines(
  name: string,
  baseName: string,
  params: QueryParamModel[],
): string[] {
  // Emit each arg on its own line so the output matches Biome's preferred
  // multi-line function-signature formatting. This keeps generated files
  // stable under `biome check --write`.
  const lines = [`export async function ${name}(`];
  if (params.length > 0) {
    lines.push(`  db: Client | Pool | PoolClient,`);
    lines.push(`  params: ${baseName}Params,`);
  } else {
    lines.push(`  db: Client | Pool | PoolClient,`);
  }
  return lines;
}

function renderParamArray(params: QueryParamModel[]): string {
  if (params.length === 0) return "[]";
  return `[${params.map((p) => `params.${p.name}`).join(", ")}]`;
}

function renderFunctionReturningRows(
  name: string,
  baseName: string,
  params: QueryParamModel[],
  rowTypeName: string,
): string {
  const signature = renderSignatureLines(name, baseName, params);
  const paramArray = renderParamArray(params);
  return [
    ...signature,
    `): Promise<${rowTypeName}[]> {`,
    `  const result = await db.query<${rowTypeName}>(SQL, ${paramArray});`,
    `  return result.rows;`,
    `}`,
  ].join("\n");
}

function renderFunctionCommand(
  name: string,
  baseName: string,
  params: QueryParamModel[],
): string {
  const signature = renderSignatureLines(name, baseName, params);
  const paramArray = renderParamArray(params);
  return [
    ...signature,
    `): Promise<{ rowCount: number }> {`,
    `  const result = await db.query(SQL, ${paramArray});`,
    `  return { rowCount: result.rowCount ?? 0 };`,
    `}`,
  ].join("\n");
}

export function renderTypescript(
  model: QueryModel,
  options: RenderOptions = {},
): string {
  const multilineSql = options.multilineSql ?? true;
  const baseName = capitalize(model.name);

  // Collect every TS type expression that might contain hoistable imports.
  const expressions: string[] = [];
  for (const p of model.params) expressions.push(p.tsType);
  if (model.rowFields) {
    for (const f of model.rowFields) expressions.push(f.tsType);
  }
  const { rewritten, importLines } = hoistImports(expressions);

  // Replace param/row types with the rewritten versions (in order).
  let idx = 0;
  const rewrittenParams = model.params.map((p) => ({
    ...p,
    tsType: rewritten[idx++] ?? p.tsType,
  }));
  const rewrittenRowFields =
    model.rowFields === null
      ? null
      : model.rowFields.map((f) => ({
          ...f,
          tsType: rewritten[idx++] ?? f.tsType,
        }));

  const sections: string[] = [];
  sections.push(renderHeader(model.sourceBasename, model.sourceHash));

  // pg runtime import — always present.
  sections.push('import type { Client, Pool, PoolClient } from "pg";');

  // Hoisted type imports from @json annotations, if any.
  if (importLines.length > 0) {
    sections.push(importLines.join("\n"));
  }

  const paramsType = renderParamsType(baseName, rewrittenParams);
  if (paramsType) sections.push(paramsType);

  if (rewrittenRowFields !== null) {
    sections.push(renderRowType(baseName, rewrittenRowFields));
  }

  sections.push(renderSqlConst(model.sql, multilineSql));

  if (rewrittenRowFields !== null) {
    sections.push(
      renderFunctionReturningRows(
        model.name,
        baseName,
        rewrittenParams,
        `${baseName}Row`,
      ),
    );
  } else {
    sections.push(renderFunctionCommand(model.name, baseName, rewrittenParams));
  }

  // Separate each section by a blank line, end with a trailing newline.
  return `${sections.join("\n\n")}\n`;
}
