/**
 * Content-hash utilities for the freshness check.
 *
 * The hash is `sha256(sourceBytes)` truncated to 16 hex chars (64 bits —
 * more than enough collision resistance for a single repo). It's embedded
 * in the header of each generated `.ts` file so `--check` mode can
 * verify staleness without re-running Parse/Describe just to compare
 * outputs.
 *
 * The hash covers the *source* `.sql` only, not the generated output.
 * That way upgrading `@nubase/pg` doesn't invalidate every file — CI
 * asks the narrower question "does the .ts correspond to the .sql?"
 * rather than "was this produced by the exact current generator?".
 */

import { createHash } from "node:crypto";

export function hashSource(source: string): string {
  return createHash("sha256").update(source, "utf8").digest("hex").slice(0, 16);
}

const HASH_RE = /\/\/\s*Hash:\s*sha256:([a-f0-9]{16})\b/;

/**
 * Extract the content hash from a generated `.ts` file's header.
 * Returns `null` if the header is missing or malformed — callers treat
 * that as "not a generated file" (or "stale").
 */
export function extractHashFromGeneratedFile(content: string): string | null {
  const match = content.match(HASH_RE);
  return match?.[1] ?? null;
}

const GENERATED_HEADER_MARKER = "Generated by @nubase/pg";

/**
 * Does this `.ts` file look like one we generated? Used by orphan cleanup
 * to avoid deleting hand-written `.ts` files that happen to live in the
 * data-layer directory.
 */
export function isGeneratedFile(content: string): boolean {
  return content.includes(GENERATED_HEADER_MARKER);
}
