import { describe, expect, it } from "vitest";
import {
  extractHashFromGeneratedFile,
  hashSource,
  isGeneratedFile,
} from "./hash";

describe("hashSource", () => {
  it("returns 16 hex chars", () => {
    const h = hashSource("SELECT 1");
    expect(h).toHaveLength(16);
    expect(h).toMatch(/^[a-f0-9]+$/);
  });

  it("is deterministic", () => {
    expect(hashSource("SELECT 1")).toBe(hashSource("SELECT 1"));
  });

  it("produces different hashes for different inputs", () => {
    expect(hashSource("SELECT 1")).not.toBe(hashSource("SELECT 2"));
  });

  it("handles empty input", () => {
    const h = hashSource("");
    expect(h).toHaveLength(16);
  });

  it("handles unicode", () => {
    const h = hashSource("SELECT 'héllo'");
    expect(h).toHaveLength(16);
    expect(h).toMatch(/^[a-f0-9]+$/);
  });
});

describe("extractHashFromGeneratedFile", () => {
  it("extracts the hash from a well-formed header", () => {
    const content = `// ───────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: foo.sql
// Hash:   sha256:deadbeefcafef00d
// ───────────────────

export const SQL = "SELECT 1";
`;
    expect(extractHashFromGeneratedFile(content)).toBe("deadbeefcafef00d");
  });

  it("returns null when there is no hash", () => {
    expect(extractHashFromGeneratedFile("// Just a comment")).toBeNull();
  });

  it("returns null for a malformed hash (wrong length)", () => {
    const content = "// Hash:   sha256:tooshort";
    expect(extractHashFromGeneratedFile(content)).toBeNull();
  });

  it("handles variable spacing around the hash", () => {
    const content = "// Hash: sha256:deadbeefcafef00d";
    expect(extractHashFromGeneratedFile(content)).toBe("deadbeefcafef00d");
  });
});

describe("isGeneratedFile", () => {
  it("recognizes a generated file via the header marker", () => {
    expect(isGeneratedFile("// Generated by @nubase/pg. DO NOT EDIT.")).toBe(
      true,
    );
  });

  it("rejects hand-written files", () => {
    expect(isGeneratedFile("export const foo = 1;")).toBe(false);
  });
});
