/**
 * Walk `data-layer/` for `.ts` files whose sibling `.sql` no longer exists,
 * and delete them. Only files identified as ours (by the
 * `Generated by @nubase/pg` header marker) are touched — hand-written `.ts`
 * files without the header are always preserved.
 *
 * Sibling identification is purely by filename: `tickets/getTicket.ts` is
 * an orphan if `tickets/getTicket.sql` is missing.
 */

import { readdir, readFile, stat, unlink } from "node:fs/promises";
import * as path from "node:path";
import { isGeneratedFile } from "./hash.js";

export interface OrphanReport {
  /** Absolute paths of `.ts` files deleted. */
  deleted: string[];
  /** Absolute paths of `.ts` files that looked orphaned but weren't ours. */
  skippedHandwritten: string[];
}

const SKIP_DIR_NAMES = new Set(["node_modules", ".git", "dist", "build"]);

async function walk(dir: string, out: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIR_NAMES.has(entry.name)) continue;
      await walk(full, out);
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".ts")) {
      out.push(full);
    }
  }
}

async function sqlExists(tsPath: string): Promise<boolean> {
  const sqlPath = tsPath.replace(/\.ts$/, ".sql");
  try {
    await stat(sqlPath);
    return true;
  } catch {
    return false;
  }
}

export async function cleanOrphans(
  dataLayerDir: string,
  { dryRun = false }: { dryRun?: boolean } = {},
): Promise<OrphanReport> {
  const absRoot = path.resolve(dataLayerDir);
  const tsFiles: string[] = [];
  try {
    await walk(absRoot, tsFiles);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") {
      return { deleted: [], skippedHandwritten: [] };
    }
    throw e;
  }

  const deleted: string[] = [];
  const skippedHandwritten: string[] = [];

  for (const tsPath of tsFiles) {
    if (await sqlExists(tsPath)) continue;

    let content: string;
    try {
      content = await readFile(tsPath, "utf8");
    } catch {
      continue;
    }

    if (!isGeneratedFile(content)) {
      skippedHandwritten.push(tsPath);
      continue;
    }

    if (!dryRun) {
      await unlink(tsPath);
    }
    deleted.push(tsPath);
  }

  return { deleted, skippedHandwritten };
}
