import { access, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { cleanOrphans } from "./orphan-cleanup";

const GENERATED_HEADER = `// ──────────────────────
// Generated by @nubase/pg. DO NOT EDIT.
// Source: foo.sql
// Hash:   sha256:deadbeefcafef00d
// ──────────────────────

`;

describe("cleanOrphans", () => {
  let tmp: string;

  beforeEach(async () => {
    tmp = await mkdtemp(path.join(os.tmpdir(), "nubase-orphan-"));
  });

  afterEach(async () => {
    await rm(tmp, { recursive: true, force: true });
  });

  async function write(relPath: string, content: string): Promise<void> {
    const abs = path.join(tmp, relPath);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, content, "utf8");
  }

  async function exists(relPath: string): Promise<boolean> {
    try {
      await access(path.join(tmp, relPath));
      return true;
    } catch {
      return false;
    }
  }

  it("returns an empty report for a clean tree", async () => {
    await write("tickets/getTicket.sql", "SELECT 1");
    await write(
      "tickets/getTicket.ts",
      `${GENERATED_HEADER}export const x = 1;`,
    );
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toEqual([]);
    expect(report.skippedHandwritten).toEqual([]);
    expect(await exists("tickets/getTicket.ts")).toBe(true);
  });

  it("deletes a generated .ts whose .sql sibling is missing", async () => {
    await write(
      "tickets/deletedQuery.ts",
      `${GENERATED_HEADER}export const x = 1;`,
    );
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toHaveLength(1);
    expect(report.deleted[0]).toContain("deletedQuery.ts");
    expect(await exists("tickets/deletedQuery.ts")).toBe(false);
  });

  it("preserves hand-written .ts files without the generated header", async () => {
    await write("tickets/helper.ts", "export function helper() { return 42; }");
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toEqual([]);
    expect(report.skippedHandwritten).toHaveLength(1);
    expect(await exists("tickets/helper.ts")).toBe(true);
  });

  it("does not delete files when the .sql sibling exists", async () => {
    await write("tickets/kept.sql", "SELECT 1");
    await write("tickets/kept.ts", `${GENERATED_HEADER}export const x = 1;`);
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toEqual([]);
    expect(await exists("tickets/kept.ts")).toBe(true);
  });

  it("supports dry-run mode (reports but does not delete)", async () => {
    await write("tickets/orphan.ts", `${GENERATED_HEADER}export const x = 1;`);
    const report = await cleanOrphans(tmp, { dryRun: true });
    expect(report.deleted).toHaveLength(1);
    expect(await exists("tickets/orphan.ts")).toBe(true);
  });

  it("handles an empty data-layer directory gracefully", async () => {
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toEqual([]);
  });

  it("handles a non-existent data-layer directory gracefully", async () => {
    const report = await cleanOrphans(path.join(tmp, "nope"));
    expect(report.deleted).toEqual([]);
  });

  it("finds orphans in nested context folders", async () => {
    await write(
      "tickets/deep/nested/orphan.ts",
      `${GENERATED_HEADER}export const x = 1;`,
    );
    const report = await cleanOrphans(tmp);
    expect(report.deleted).toHaveLength(1);
  });
});
