// Auto-generated by `nubase pull` — do not edit manually.

export type Ticket = {
  id: number;
  workspace_id: number;
  title: string;
  description: string | null;
  assignee_email: string | null;
};

export type TicketInsert = {
  workspace_id: number;
  title: string;
  description?: string | null;
  assignee_email?: string | null;
};

export type TicketUpdate = {
  workspace_id?: number;
  title?: string;
  description?: string | null;
  assignee_email?: string | null;
};
